version: 2.1

executors:
  maven:
    docker:
      - image: cimg/openjdk:11.0.26
        user: root

workflows:
  test-and-build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
          context:
            - cm-cloudsmith
            - cm-team-github
      - publish-cloudsmith:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
          context:
            - cm-cloudsmith
            - cm-team-github

jobs:
  build:
    working_directory: ~/jax-rs-build-info-resource
    executor: maven
    steps:
      - checkout
      - run:
          name: Maven Verify
          command: |
            mkdir /root/.m2/
            curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3.raw" -v -o ~/.m2/settings.xml -L "https://raw.githubusercontent.com/Financial-Times/cloudsmith-settings/main/public-settings.xml"
            mvn clean verify jacoco:report coveralls:report -DrepoToken=${COVERALLS_TOKEN}
            rm -rf /root/.m2/*
  publish-cloudsmith:
    working_directory: ~/jax-rs-build-info-resource
    executor: maven
    steps:
      - checkout:
          path: ~/jax-rs-build-info-resource
      - run:
          name: Publish Tag to CloudSmith repository
          command: |
            mkdir /root/.m2/
            curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3.raw" -v -o ~/.m2/settings.xml -L "https://raw.githubusercontent.com/Financial-Times/cloudsmith-settings/main/public-settings.xml"
            mvn versions:set -DnewVersion=${CIRCLE_TAG}
            mvn versions:commit
            mvn deploy
            rm -rf /root/.m2/*